apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "helm.fullname" . }}
spec:
  type: LoadBalancer
  loadBalancerClass: metallb
  ports:
    - port: 56700
      targetPort: peer
      protocol: UDP
      name: peer
    - port: 56750
      targetPort: broadcast
      protocol: UDP
      name: broadcast
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
